---
title: "DID analysis"
output: html_document
date: "2025-04-07"
---

```{r}
library(tidyverse)
library(ggplot2)
library(readxl)

options(scipen = 999)
file_path <- dirname(getwd())
```

```{r}
#Load in Illinois Crime Stats
Illinois_Crime_Stats <- read_excel(file.path(file_path, "Raw Data", "Illinois Crime Stats.xlsx"))
View(Illinois_Crime_Stats)
```

```{r}
# DID analysis - using CPD reported Crime statistics
reported_DID <- Illinois_Crime_Stats |>
  filter(Year != 2020) |>
  select(Year, Non_Chicago_Reported_TIC, CPD_Reported_TIC) |>
  rename(Non_Chicago = Non_Chicago_Reported_TIC,
         Chicago = CPD_Reported_TIC)
```

```{r}
reported_DID <- reported_DID |>
  pivot_longer(cols = c(Non_Chicago, Chicago), names_to = "Area") |>
  #create a dummy variable for when the treatment started
  mutate(time = ifelse(Year > 2012, 1, 0)) |>
  #create a dummy variable for geographic area treated
  mutate(treated = ifelse(Area == "Chicago", 1, 0)) |>
  #create an interaction between time and treated variables
  mutate(did = time*treated)
```

```{r}
didreg = lm(value ~ treated + time + did, data = reported_DID)
summary(didreg)
```

```{r}
didreg1 = lm(value ~ treated*time, data = reported_DID)
summary(didreg1)
```

```{r}
library(stargazer)

# Export results to LaTeX (or Word)
stargazer(didreg, type = "latex", out = "DID_results.tex")  # To export LaTeX
# stargazer(fe_model, type = "text", out = "DID_results.txt")  # To export text
```

```{r}
# DID analysis - using CPD reported Crime Rate for population
reported_rate_DID <- Illinois_Crime_Stats |>
  filter(Year != 2020) |>
  select(Year, Illinois_TIX_Offenses, Illinois_Population, Non_Chicago_Reported_TIC, Non_Chicago_Population, CPD_Reported_TIC, `CPD_Reported Population`) |>
  mutate(Non_Chicago_CrimePer = Non_Chicago_Reported_TIC/(Non_Chicago_Population/100000),
         Chicago_CrimePer = CPD_Reported_TIC/(`CPD_Reported Population`/100000)) |>
  select(Year, Non_Chicago_CrimePer, Chicago_CrimePer)
```

```{r}
reported_rate_DID <- reported_rate_DID |>
  pivot_longer(cols = c(Non_Chicago_CrimePer, Chicago_CrimePer), names_to = "Area") |>
  #create a dummy variable for when the treatment started
  mutate(time = ifelse(Year > 2012, 1, 0)) |>
  #create a dummy variable for geographic area treated
  mutate(treated = ifelse(Area == "Chicago_CrimePer", 1, 0)) |>
  #create an interaction between time and treated variables
  mutate(did = time*treated)
```

```{r}
didreg_rate = lm(value ~ treated + time + did, data = reported_rate_DID)
summary(didreg_rate)
```

```{r}
didreg1_rate = lm(value ~ treated*time, data = reported_rate_DID)
summary(didreg1_rate)
```

```{r}
library(stargazer)

# Export results to LaTeX (or Word)
stargazer(didreg_rate, type = "latex", out = "DID_results.tex")  # To export LaTeX
# stargazer(fe_model, type = "text", out = "DID_results.txt")  # To export text
```

