---
title: "Distict_Level_Crimes_Analyses"
output: html_document
date: "2025-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(colorspace)
library(tmap)
library(leaflet)
library(sf)
library(showtext)
library(classInt)

options(scipen = 999)
file_path <- file.path(dirname(getwd()), "Thesis")
file_path
palette_30 <- qualitative_hcl(30, palette = "Dark 3")  # Or try "Set 2", "Harmonic", etc.
```

```{r}
#load in Crime Dataset from 2010-Present
Crimes_2010_to_Present <- read_csv(file.path(file_path, "Cleaned Data",  "Crimes_-_2010_to_Present_20241114.csv"))

#load in IUCR Codes Dataset
IUCR_Codes <- read.csv(file.path(file_path,"Raw Data", "Chicago_Police_Department_-_Illinois_Uniform_Crime_Reporting__IUCR__Codes_20250306.csv"))

#load in District Population Dataset
District_Population_Ethnicity <- read.csv(file.path(file_path,"Cleaned Data", "District Population and Ethnicity.csv"))



Crimes_2010_Present_TIC <- left_join(Crimes_2010_to_Present, IUCR_Codes, by = "IUCR") |>
  filter(Year < 2020) |>
  filter(INDEX.CODE == "I")
```


--------------------------------------------------------------------------------
#District Breakdown

```{r, eval = FALSE}
#Add a Boolean that signifies if the reported incident was a violent crime
Crimes_2010_Present <- left_join(Crimes_2010_to_Present, IUCR_Codes, by = "IUCR") |>
  filter(Year < 2020)
```

```{r, eval = FALSE}
#Creates Total Crime Count for Each district from 2010-2019
District_Crime_Level_Year <- Crimes_2010_Present |>
  group_by(District, Year) |>
  summarise(Total_Crime = n_distinct(`Case Number`),
            Violent = sum(Violent == 1, na.rm = TRUE),
            Arrests = sum(Arrest == 'false', na.rm = TRUE))
```

```{r, eval = FALSE}
#Create TIC counts for Each District from 2010-2019
Year_District_Crimes_TIC <- Crimes_2010_Present |>
  #INDEX.CODE (from the IUCR) dataset indicates if crimes are used in TIC Count
  filter(INDEX.CODE == "I") |>
  group_by(District, Year) |>
  summarise(
    TIC = n_distinct(`Case Number`),
    Violent = sum(Violent == 1, na.rm = TRUE),
    Arrests = sum(Arrest == TRUE, na.rm = TRUE))
```

```{r, eval = FALSE}
#Join Total Crime Counts and Total Index Crime
left_join(District_Crime_Level_Year, Year_District_Crimes_TIC, by = c("District", "Year")) |>
  select(District, Year, TIC) |>
  pivot_wider(names_from = (District), values_from = TIC)

#Export File
write.csv(left_join(District_Crime_Level_Year, Year_District_Crimes_TIC, by = c("District", "Year")) |>
  select(District, Year, TIC), file = "District_TIC_byYear.csv")
```

```{r, eval = FALSE}
#Join Total Crime Counts and Total Index Crime
Year_District_Crimes_TIC |>
  select(District, Year, TIC) |>
  pivot_wider(names_from = (District), values_from = TIC)

#Export File
write.csv(left_join(District_Crime_Level_Year, Year_District_Crimes_TIC, by = c("District", "Year")) |>
  select(District, Year, Total_Crime, TIC), file = "District_TIC_byYear.csv")
```

```{r, eval = FALSE}
#Creates a Crime per 1000 Rate Column
Year_District_Crimes_TIC <- Year_District_Crimes_TIC %>%
  mutate(District = as.integer(District))

District_population <- left_join(Year_District_Crimes_TIC, District_Population_Ethnicity, by = join_by(District)) |>
  mutate(Crime_per_1000 = TIC/(`Total.Population`/1000))

write.csv(District_population, "District_level.csv")
```

```{r, eval = FALSE}
District_population |>
  filter(District != 31) |>
  pivot_longer(cols = c(Crime_per_1000, TIC), names_to = 'Type', values_to = 'Count') |>
  ggplot(aes(x = Year, y = Count, color = Type)) +  # use color for line plot
  geom_line() +
  facet_wrap(~ District)
```

```{r, eval = FALSE}
#Averages Total Crime and Total Index Crime across 2010-2019 for each district
District_population |>
  group_by(District) |>
  summarise(Average_Crime = mean(`TIC`),
            Average_Crimeper1000 = mean(Crime_per_1000))
```


```{r, eval = FALSE}
library(knitr)
kable((District_population |>
  group_by(District) |>
  summarise(Average_Crime = mean(`TIC`),
            Average_Crimeper1000 = mean(Crime_per_1000))), format = "latex", digits = 2, caption = "Average Crime by District")
```

```{r, eval = FALSE}
ggplot(District_population, aes(x = Year, y = Violent, color = factor(District))) +
  geom_line() +
  geom_point(size = 0.5) +
  scale_color_viridis_d(option = "turbo", begin = 0, end = 1) +
  scale_x_continuous(breaks = seq(2010, 2020, by = 1)) +
  labs(title = "Violent Crime Trends by District",
       x = "Year",
       y = "Violent Crime Count",
       color = "District") +
  theme_minimal()
```

```{r, eval = FALSE}
(District_population |>
  group_by(District) |>
  summarise(Average_Crime = mean(`TIC`),
            Average_Crimeper1000 = mean(Crime_per_1000)))


ggplot(District_population, aes(x = Year, y = Crime_per_1000, color = factor(District))) +
  geom_line() +
  geom_point(size = 0.5) +
  scale_color_manual(values = palette_30)+
  scale_x_continuous(breaks = seq(2010, 2020, by = 1)) +
  labs(title = "Violent Crime Trends by District",
       x = "Year",
       y = "Violent Crime Count",
       color = "District") +
  theme_minimal()
```


```{r, eval = FALSE}
Year_Crimes <- Crimes_2010_Present |>
  group_by(Year) |>
  summarise(Total_Crime = n(),
            Violent = sum(Violent == 1, na.rm = TRUE),
            Arrests = sum(Arrest == 'false', na.rm = TRUE),
            Crime_to_Arrest_Ratio = Violent / Arrests)
```


```{r, eval = FALSE}
Year_Crimes_NOT <- Crimes_2010_Present |>
  filter(District != 31) |>
  filter(!`Primary Type` %in% c("HOMICIDE", "CRIMINAL SEXUAL ASSAULT", "ROBBERY", 
                             "BATTERY", "ASSAULT", "BURGLARY", "THEFT", 
                             "MOTOR VEHICLE THEFT", "ARSON", "HUMAN TRAFFICKING")) |>
  group_by(Year) |>
  summarise(
    Total_Crime = n(),
    Violent = sum(Violent == 1, na.rm = TRUE),
    Arrests = sum(Arrest == TRUE, na.rm = TRUE),  # or Arrest == FALSE if you meant non-arrests
    Crime_to_Arrest_Ratio = Violent / Arrests
  )
```


```{r, eval = FALSE}
District_Crime_Level <- Crimes_2010_Present |>
  group_by(District) |>
  summarise(Violent = sum(Violent == 1, na.rm = TRUE),
            Arrests = sum(Arrest == 'false', na.rm = TRUE),
            Crime_to_Arrest_Ratio = Violent / Arrests) |>
  #calculate the z-score, how many sd away from the mean
  mutate(
    Violent_Z = (Violent - mean(Violent)) / sd(Violent),
    Arrests_Z = (Arrests - mean(Arrests)) / sd(Arrests)
  ) |>
  mutate(z_scores = Violent_Z + Arrests_Z)
3
#COMBINE WITH POPULATION DATA

```

```{r, eval = FALSE}
District_Crime_Level_Year$Year <- as.numeric(District_Crime_Level_Year$Year)
District_Crime_Level_Year$District <- as.factor(District_Crime_Level_Year$District)
library(viridis)
library(ggrepel)
```

```{r, eval = FALSE}
ggplot(District_Crime_Level_Year, aes(x = Year, y = Violent, color = District)) +
  geom_line() +
  geom_point(size = 0.5) +
  scale_color_viridis_d(option = "turbo", begin = 0, end = 1)+
  scale_x_continuous(breaks = seq(2010, 2020, by = 1))+
  labs(title = "Violent Crime Trends by District",
       x = "Year",
       y = "Violent Crime Count",
       color = "District",
       linetype = "District") +
  theme_minimal()
```

```{r, eval = FALSE}
top_3 <- District_Crime_Level_Year %>%
  filter(Year == 2020) %>%
  arrange(desc(Violent)) %>%
  slice_head(n = 3)  # Select only the top 3 highest crime districts

ggplot(District_Crime_Level_Year, aes(x = Year, y = Violent, color = District)) +
  geom_line() +  
  geom_text(data = top_3, aes(label = District), 
            hjust = -0.1, vjust = 0.5, size = 5) + # Labels only for top 3
  scale_color_viridis_d(option = "turbo") +  
  scale_x_continuous(breaks = seq(2010, 2020, by = 1)) +  
  labs(title = "Violent Crime Trends by District",
       x = "Year",
       y = "Violent Crime Count",
       color = "District") +
  theme_minimal()
```

```{r, eval = FALSE}
#Strategic_Subject_List_Historical <- read_csv("~/2025 Spring/Thesis/Strategic_Subject_List_-_Historical_20241107.csv")
```

```{r, eval = FALSE}

#left_join(SSL_District, SSL_top50)

#ggplot(left_join(SSL_District, SSL_top50), aes(x = District, y = mean)) +
#  geom_line() +  
#  scale_color_viridis_d(option = "turbo") +  
#  scale_x_continuous(breaks = seq(1, 25, by = 1))
#  labs(title = "SSL Top 50 Mean by District",
#       x = "District",
#       y = "Mean of top 50 individuals with the highest SSL score") +
#  theme_minimal()

```

----------------------------
#District Map

```{r, eval = FALSE}
District_Summaries <- District_population |>
  group_by(District) |>
  summarise(TIC = mean(TIC),
            Crime_per_1000 = mean(Crime_per_1000))
```

```{r, eval = FALSE}
PoliceDistrictBoundaries_Current <- read_csv(file.path(file_path, "Shapefiles",  "PoliceDistrictBoundaries_Current.csv"))
```
```{r, eval = FALSE}
PoliceDistrictBoundaries_Current <- read_sf(file.path(file_path, "Shapefiles",  "PoliceDistrictBoundaries_Current.csv"))
```

```{r, eval = FALSE}
PoliceDistrictBoundaries_Current <- PoliceDistrictBoundaries_Current |>
  rename(geometry = the_geom,
         District = DIST_NUM) |>
  select(geometry, District)
```

```{r, eval = FALSE}
PoliceDistrictBoundaries_Current <- st_as_sf(PoliceDistrictBoundaries_Current, wkt = "geometry")

PoliceDistrictBoundaries_Current$District <- as.integer(PoliceDistrictBoundaries_Current$District)
```

```{r, eval = FALSE}
ggplot(data = PoliceDistrictBoundaries_Current) +
  geom_sf(aes(geometry = geometry)) +
  labs(title = "Police District Boundaries")
```

```{r, eval = FALSE}
# Create breaks
breaks <- classIntervals(District_Summaries$Crime_per_1000, n = 5, style = "jenks")$brks
breaks <- breaks[2:6]

# Bin the data
District_Summaries <- District_Summaries |>
  mutate(Crime_bin = cut(Crime_per_1000, breaks = breaks, include.lowest = TRUE))

# Merge with spatial
merged <- left_join(PoliceDistrictBoundaries_Current, District_Summaries, by = "District")

# Get centroids
centroids <- st_centroid(merged)
```

```{r, eval = FALSE}
# Font setup
theme_set(theme_bw(base_family = "Cambria"))

# Reorder and relabel factor
merged$Crime_bin <- factor(
  merged$Crime_bin,
  levels = c("[0.174,39.7]", "(39.7,63.5]", "(63.5,84.1]", "(84.1,118]"),
  labels = c("Low (Less than 40 TIC)", "Moderate (40-65 TIC)", "High (65-90 TIC)", "Very High (Over 90 TIC)")
)

p4 <- c("Low (Less than 40 TIC)" = "#59c64e",
        "Moderate (40-65 TIC)" = "#fee08b",
        "High (65-90 TIC)" = "#f6bb90",
        "Very High (Over 90 TIC)" = "#E94E46")
```

```{r, eval = FALSE}
# Plot
plot <- ggplot(merged) +
  geom_sf(aes(fill = Crime_bin), color = "white", size = 0.3) +
  geom_text(
    data = centroids,
    aes(label = District, geometry = geometry),
    stat = "sf_coordinates",
    size = 4,
    color = "black"
  ) +
  scale_fill_manual(
    values = p4,
    name = "Crime Rate"
  ) +
  labs(title = "Map of Chicago Districts and Crime Rate per 1,000") #+
  #theme_bw(base_family = "Cambria") +
  
  #theme(
    legend.title = element_text(size = 16, face = "bold"),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold"),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank()
  )

ggsave("Chicago_Districts_and_Crime_Rate.png", 
       plot = plot,
       width = 4,
       height = 3)
```

```{r, eval = FALSE}
# Merge with spatial, no bins
merged2 <- left_join(PoliceDistrictBoundaries_Current, District_Summaries, by = "District")

# Get centroids
centroids <- st_centroid(merged2)
```

```{r, eval = FALSE}
theme_set(theme_bw(base_family = "Cambria"))

# Plot
#plot <- 
  ggplot(merged2) +
  geom_sf(aes(fill = Crime_per_1000), color = "white", size = 0.3) +
  geom_text(
    data = centroids,
    aes(label = District, geometry = geometry),
    stat = "sf_coordinates",
    size = 3,
    color = "black"
  ) +
scale_fill_gradientn(
  colors = c("#1a9850", "#fee08b", "#d73027"),  # Green → Yellow → Red
  name = "Crime per 1,000",
  limits = range(merged2$Crime_per_1000, na.rm = TRUE),
  na.value = "grey90"
) +
  labs(title = "Map of Chicago Districts and Crime Rate per 1,000") +
  theme(
    legend.title = element_text(face = "bold"),
    plot.title = element_text(face = "bold"),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank()
  )
    
#  theme(
#    legend.title = element_text(size = 16, face = "bold"),
#    legend.text = element_text(size = 14),
#    plot.title = element_text(size = 20, face = "bold"),
#    axis.text = element_blank(),
#   axis.ticks = element_blank(),
#    axis.title = element_blank()
#  )

#ggsave("Chicago_Districts_and_Crime_Rate.png", 
#       plot = plot,
#       width = 4,
#       height = 3)

```

-----------------
#Year Breakdown
```{r, eval = FALSE}
Year_Crimes <- Crimes_2010_Present |>
  group_by(Year) |>
  summarise(Violent = sum(Violent == 1, na.rm = TRUE),
            Arrests = sum(Arrest == 'false', na.rm = TRUE),
            Crime_to_Arrest_Ratio = Violent / Arrests) |>
  #calculate the z-score, how many sd away from the mean
  mutate(
    Violent_Z = (Violent - mean(Violent)) / sd(Violent),
    Arrests_Z = (Arrests - mean(Arrests)) / sd(Arrests)
  ) |>
  mutate(z_scores = Violent_Z + Arrests_Z)
```

```{r, eval = FALSE}
overall_trend <- District_population |>
  group_by(Year) |>
  summarise(mean = mean(Crime_per_1000))

ggplot(District_population, aes(x = Year, y = Crime_per_1000, group = District)) +
  geom_line(color = "#0072B2", size = 1) +  # Clear blue for all district lines
  geom_line(
    data = overall_trend,
    aes(x = Year, y = mean),
    inherit.aes = FALSE,
    color = "black",
    linetype = "dashed",
    size = 1
  ) +  # Dotted black line for overall trend
  scale_x_continuous(breaks = seq(2010, 2020, by = 2))+
  facet_wrap(~ District, ncol = 4) +
  labs(
    title = "Crime Rates per 1,000 by District",
    x = "Year",
    y = "Crime per 1,000"
  )

+
  theme(
    plot.title = element_text(size = 20, face = "bold"),
    axis.text = element_text(size = 15, face = "bold"),
    axis.title = element_text(size = 20, face = "bold")
  )

#ggsave("plot.jpg",
#       plot=  plot,
#       width = 3.5,
#       height = 7)
```

--------------------------------------
#District - Arrest Ratios
--------------------------------------

```{r, eval = FALSE}
Crimes_2010_Present_TIC |>
  group_by(Year, District) |>
  summarise(Violent = sum(Violent == "1", na.rm = TRUE),
            Arrests = sum(Arrest == 'TRUE', na.rm = TRUE),
            Crime_to_Arrest_Ratio = Violent / Arrests)
```

```{r, eval = FALSE}
Crimes_2010_Present_TIC |>
  filter(INDEX.CODE == "I") |>
  group_by(Year, District) |>
  summarise(count = n(),
            Arrests = sum(Arrest == 'TRUE', na.rm = TRUE),
            Crime_to_Arrest = count / Arrests) |>
  ggplot(aes(x = Year, y = Crime_to_Arrest)) +
  geom_line() +
  facet_wrap(~District)

#A higher value means fewer arrests relative to crime (i.e., more crimes happen before an arrest is made). A lower value means more arrests relative to crime (i.e., fewer crimes per arrest).
```

```{r, eval = FALSE}

TIC_arrests_ratio <- Crimes_2010_Present_TIC |>
  filter(INDEX.CODE == "I") |>
  group_by(Year, District) |>
  summarise(count = n(),
            Arrests = sum(Arrest == 'TRUE', na.rm = TRUE),
            Crime_to_Arrest_Ratio = count / Arrests) |>
  filter(!is.na(Crime_to_Arrest_Ratio), is.finite(Crime_to_Arrest_Ratio))

ggplot(TIC_arrests_ratio, aes(x = Year, y = factor(District), fill = Crime_to_Arrest_Ratio)) +
  geom_tile() +
  scale_x_continuous(breaks = unique(TIC_arrests_ratio$Year))+
  scale_fill_gradientn(
    colors = c("#1a9850", "#fee08b", "#d73027"),  # Green → Yellow → Red
    name = "Crime to Arrest Ratio",
    limits = range(TIC_arrests_ratio$Crime_to_Arrest_Ratio, na.rm = TRUE),
    na.value = "grey90"
  ) +
  theme_minimal() +
  labs(title = "Crime to Arrest Ratio Heatmap",
       x = "Year",
       y = "District") +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14, face = "bold"),
    axis.text = element_text(size = 12)
  )

```
```{r}
overall_trend_arrest_ratio <- TIC_arrests_ratio |>
  group_by(Year) |>
  summarise(mean = mean(Crime_to_Arrest_Ratio))

#TIC_arrests_ratio

TIC_arrests_ratio$District <- as.numeric(TIC_arrests_ratio$District)
  

ggplot(TIC_arrests_ratio, aes(x = Year, y = Crime_to_Arrest_Ratio, group = District)) +
  geom_line(color = "#0072B2", size = 1) +  # Clear blue for all district lines
  geom_line(
    data = overall_trend_arrest_ratio,
    aes(x = Year, y = mean),
    inherit.aes = FALSE,
    color = "black",
    linetype = "dashed",
    size = 1
  ) +  # Dotted black line for overall trend
  scale_x_continuous(breaks = seq(2010, 2020, by = 2))+
  facet_wrap(~ District, ncol = 4) +
  labs(
    title = "TIC Crime to Arrest Ratio",
    x = "Year",
    y = "Crime to Arrest Ratio"
  )
```

--------------------------------------
#COPA Complaints
--------------------------------------

```{r, eval = FALSE}
#COPA COMPLAINTS

COPA_Cases_._By_Involved_Officer_20241120 <- read_csv(file.path(file_path,"Raw Data", "COPA_Cases_-_By_Involved_Officer_20241120.csv"))

BIA_Cases_By_Involved_Officer <- read_csv(file.path(file_path,"Raw Data", "BIA_Cases_-_By_Involved_Officer_20250327.csv"))
```

```{r, eval = FALSE}
COPA_Cases_._By_Involved_Officer_20241120 |>
  mutate(COMPLAINT_DATE = as.POSIXct(COMPLAINT_DATE, format = "%m/%d/%Y %I:%M:%S %p")) |>
  filter(COMPLAINT_DATE > 01/01/2010)
```

```{r, eval = FALSE}
COPA_BIA_complaints <- left_join(COPA_Cases_._By_Involved_Officer_20241120, BIA_Cases_By_Involved_Officer, by = "LOG_NO") |>
   mutate(across(where(is.character), ~ na_if(.x, ""))) |>
  #combine columns
  mutate(COMPLAINT_DATE = COMPLAINT_DATE.x,
         CASE_TYPE = coalesce(CASE_TYPE.x, CASE_TYPE.y),
         CURRENT_STATUS = coalesce(CURRENT_STATUS.x, CURRENT_STATUS.y),
         FINDING_CODE = coalesce(FINDING_CODE.x, FINDING_CODE.y),
         BEAT = coalesce(BEAT.x, BEAT.y),
         RACE_OF_INVOLVED_OFFICER = coalesce(RACE_OF_INVOLVED_OFFICER.x, RACE_OF_INVOLVED_OFFICER.y),
         SEX_OF_INVOLVED_OFFICER = coalesce(SEX_OF_INVOLVED_OFFICER.x, SEX_OF_INVOLVED_OFFICER.y), 
         AGE_OF_INVOLVED_OFFICER = coalesce(as.character(AGE_OF_INVOLVED_OFFICER.x), as.character(AGE_OF_INVOLVED_OFFICER.y)),
         YEARS_ON_FORCE_OF_INVOLVED_OFFICER = coalesce(as.character(YEARS_ON_FORCE_OF_INVOLVED_OFFICER.x), as.character(YEARS_ON_FORCE_OF_INVOLVED_OFFICER.y)),
         COMPLAINT_DATE = as.POSIXct(COMPLAINT_DATE, format = "%m/%d/%Y %I:%M:%S %p"),
         COMPLAINT_YEAR = year(as.Date(COMPLAINT_DATE))) |>
  #select combined columns
  select(LOG_NO, COMPLAINT_DATE, ASSIGNMENT, CASE_TYPE, CURRENT_STATUS, CURRENT_CATEGORY, FINDING_CODE, POLICE_SHOOTING, BEAT, RACE_OF_INVOLVED_OFFICER, SEX_OF_INVOLVED_OFFICER, AGE_OF_INVOLVED_OFFICER, YEARS_ON_FORCE_OF_INVOLVED_OFFICER, COMPLAINT_YEAR) |>
  #filter complaints from 2010-2020
  filter(COMPLAINT_YEAR >= 2010 & COMPLAINT_YEAR <= 2020)|>
  filter(BEAT != "Unknown") |>
  filter(BEAT != "6100") |>
  # Separate multiple beats into multiple rows
  separate_rows(BEAT, sep = " \\| ") |>
  # Clean white space
  mutate(BEAT = str_trim(BEAT)) |>
  #filter out cases with District == 0 
  filter(BEAT != "0") |>
  filter(!is.na(BEAT)) |>
  # Add leading zero if beat is only 3 digits
  mutate(BEAT = if_else(nchar(BEAT) == 3, paste0("0", BEAT), BEAT)) |>
  # Extract district: first two digits
  mutate(DISTRICT = substr(BEAT, 1, 2)) |>
  mutate(DISTRICT = ifelse((DISTRICT == 13), 12, DISTRICT)) |>
  #consolidate district 21 into 2
  mutate(DISTRICT = ifelse((DISTRICT == 21), 2, DISTRICT)) |>
  #consolidate district 23 into 19
  mutate(DISTRICT = ifelse((DISTRICT == "23"), 19, DISTRICT)) |>
  mutate(DISTRICT = ifelse((DISTRICT == "2"), "02", DISTRICT)) 

#81464 total complaints logged
#37810 after filtering out complaints with NA beats
#37370 after filtering out rest of non loggable beats
```

```{r, eval = FALSE}
test <- COPA_BIA_complaints |>
  group_by(DISTRICT, COMPLAINT_YEAR) |>
  summarise(count = n())

test <- test |>
  group_by(COMPLAINT_YEAR) |>
  summarise(Count = median(count)) |>
  mutate(DISTRICT = "All") |>
  select(DISTRICT, COMPLAINT_YEAR, Count)
```

```{r, eval = FALSE}

#Overall median of complaints for each district: 1289
#Overall mean of complaints for each district: 1384

COPA_BIA_complaints_counts <- COPA_BIA_complaints |>
  group_by(DISTRICT, COMPLAINT_YEAR) |>
  summarise(Count = n()) 

COPA_BIA_complaints_counts |>
  group_by(DISTRICT) |>
  summarize(median = median(Count))
```

```{r, eval = FALSE}
district_levels_1 <- c("All", "01", "02", "03", "04", "05")

rbind(COPA_BIA_complaints_counts, test) |>
  filter(DISTRICT %in% district_levels_1) |>
  mutate(DISTRICT = factor(DISTRICT, levels = district_levels_1)) |>
  ggplot(aes(x = COMPLAINT_YEAR, y = Count, color = DISTRICT, linetype = DISTRICT)) +
  geom_point(size = 1.3) +
  geom_line(width = 1.15) +
  scale_color_manual(
    values = c("All" = "black", 
               "01" = "#1f77b4", 
               "02" = "#ff7f0e", 
               "03" = "#2ca02c", 
               "04" = "#d62728", 
               "05" = "#9467bd")
  ) +
  scale_linetype_manual(
    values = c("All" = "dashed", 
               "01" = "solid",
               "02" = "solid",
               "03" = "solid",
               "04" = "solid",
               "05" = "solid")
  ) +
  scale_x_continuous(breaks = 2010:2019, limits = c(2010, 2019))+
  scale_y_continuous(limits = c(0, 600))+
  guides(
    color = guide_legend(
      override.aes = list(
        color = c("black", "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"),
        linetype = c("dashed", "solid", "solid", "solid", "solid", "solid")
      )
    ),
    linetype = "none"
  ) +
  labs(title = "COPA/BIA Complaints Over Time for District 1-5",
       x = "Year",
       y = "Number of Complaints",
       color = "District") +
  theme(
    legend.title = element_text(size = 16, face = "bold"),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold"),
    axis.text = element_text(size = 15, face = "bold"),
    axis.title = element_text(size = 20, face = "bold")
  )
```

```{r, eval = FALSE}
district_levels_2 <- c("All", "06", "07", "08", "09", "10", "11")

rbind(COPA_BIA_complaints_counts, test) |>
  filter(DISTRICT %in% district_levels_2) |>
  mutate(DISTRICT = factor(DISTRICT, levels = district_levels_2)) |>
  ggplot(aes(x = COMPLAINT_YEAR, y = Count, color = DISTRICT, linetype = DISTRICT)) +
  geom_point(size = 1.3) +
  geom_line(width = 1.15) +
scale_color_manual(
  values = c("All" = "black", 
             "06" = "#1f77b4", 
             "07" = "#ff7f0e", 
             "08" = "#2ca02c", 
             "09" = "#d62728", 
             "10" = "#9467bd",
             "11" = "#17becf")
)+
scale_linetype_manual(
  values = c("All" = "dashed", 
             "06" = "solid",
             "07" = "solid",
             "08" = "solid",
             "09" = "solid",
             "10" = "solid",
             "11" = "solid")
)+
  scale_x_continuous(breaks = 2010:2019, limits = c(2010, 2019))+
  scale_y_continuous(limits = c(0, 600))+
  guides(
    color = guide_legend(
      override.aes = list(
        color = c("black", "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#17becf"),
        linetype = c("dashed", "solid", "solid", "solid", "solid", "solid", "solid")
      )
    ),
    linetype = "none"
  ) +
  labs(title = "COPA/BIA Complaints Over Time for District 6-11",
       x = "Year",
       y = "Number of Complaints",
       color = "District") +
    theme(
    legend.title = element_text(size = 16, face = "bold"),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold"),
    axis.text = element_text(size = 15, face = "bold"),
    axis.title = element_text(size = 20, face = "bold")
  )

```

```{r, eval = FALSE}
district_levels_3 <- c("All", "12", "14", "15", "16", "17", "18")

rbind(COPA_BIA_complaints_counts, test) |>
  filter(DISTRICT %in% district_levels_3) |>
  mutate(DISTRICT = factor(DISTRICT, levels = district_levels_3)) |>
  ggplot(aes(x = COMPLAINT_YEAR, y = Count, color = DISTRICT, linetype = DISTRICT)) +
  geom_point(size = 1.3) +
  geom_line(width = 1.15) +
scale_color_manual(
  values = c("All" = "black", 
             "12" = "#1f77b4", 
             "14" = "#ff7f0e", 
             "15" = "#2ca02c", 
             "16" = "#d62728", 
             "17" = "#9467bd",
             "18" = "#17becf")
)+
scale_linetype_manual(
  values = c("All" = "dashed", 
             "12" = "solid",
             "14" = "solid",
             "15" = "solid",
             "16" = "solid",
             "17" = "solid",
             "18" = "solid")
)+
  scale_x_continuous(breaks = 2010:2019, limits = c(2010, 2019))+
  scale_y_continuous(limits = c(0, 600)) +
  guides(
    color = guide_legend(
      override.aes = list(
        color = c("black", "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#17becf"),
        linetype = c("dashed", "solid", "solid", "solid", "solid", "solid", "solid")
      )
    ),
    linetype = "none"
  ) +
  labs(title = "COPA/BIA Complaints Over Time for District 12-18",
       x = "Year",
       y = "Number of Complaints",
       color = "District") +
    theme(
    legend.title = element_text(size = 16, face = "bold"),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold"),
    axis.text = element_text(size = 15, face = "bold"),
    axis.title = element_text(size = 20, face = "bold")
  )
```

```{r, eval = FALSE}
district_levels_4 <- c("All", "19", "20", "22", "24", "25", "31")

rbind(COPA_BIA_complaints_counts, test) |>
  filter(DISTRICT %in% district_levels_4) |>
  mutate(DISTRICT = factor(DISTRICT, levels = district_levels_4)) |>
  ggplot(aes(x = COMPLAINT_YEAR, y = Count, color = DISTRICT, linetype = DISTRICT)) +
  geom_point(size = 1.3) +
  geom_line(width = 1.15) +
scale_color_manual(
  values = c("All" = "black", 
             "19" = "#1f77b4", 
             "20" = "#ff7f0e", 
             "22" = "#2ca02c", 
             "24" = "#d62728", 
             "25" = "#9467bd",
             "31" = "#17becf")
)+
scale_linetype_manual(
  values = c("All" = "dashed", 
             "19" = "solid",
             "20" = "solid",
             "22" = "solid",
             "24" = "solid",
             "25" = "solid",
             "31" = "solid")
)+
  scale_x_continuous(breaks = 2010:2019, limits = c(2010, 2019))+
  scale_y_continuous(limits = c(0, 600))+
  guides(
    color = guide_legend(
      override.aes = list(
        color = c("black", "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#17becf"),
        linetype = c("dashed", "solid", "solid", "solid", "solid", "solid", "solid")
      )
    ),
    linetype = "none"
  ) +
  labs(title = "COPA/BIA Complaints Over Time for District 19-25, 31",
       x = "Year",
       y = "Number of Complaints",
       color = "District") +
    theme(
    legend.title = element_text(size = 16, face = "bold"),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold"),
    axis.text = element_text(size = 15, face = "bold"),
    axis.title = element_text(size = 20, face = "bold")
  )
```


```{r, eval = FALSE}
COPA_BIA_complaints |>
  #filters out na cases (42477 of the entries, 52%)
  filter(!is.na(CASE_TYPE)) |>
  #filters out complaint with no registered beat
  filter(DISTRICT != "00" ) |>
  group_by(DISTRICT, COMPLAINT_YEAR) |>
  summarise(Count = n()) |>
ggplot(aes(x = COMPLAINT_YEAR, y = Count, fill = DISTRICT))+
  geom_line(aes(color = DISTRICT))
```

