---
title: "General Crime Dataset"
output: html_document
date: "2025-04-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(readxl)
library(stargazer)

options(scipen = 999)
file_path <- dirname(getwd())
```

```{r}
#load in Crime Dataset from 2010-Present
Crimes_2010_to_Present <- read_csv(file.path(file_path, "Cleaned Data",  "Crimes_-_2010_to_Present_20241114.csv"))

#load in IUCR Codes Dataset
IUCR_Codes <- read.csv(file.path(file_path,"Raw Data", "Chicago_Police_Department_-_Illinois_Uniform_Crime_Reporting__IUCR__Codes_20250306.csv"))

#Load in Illinois Crime Stats
Illinois_Crime_Stats <- read_excel(file.path(file_path, "Raw Data", "Illinois Crime Stats.xlsx"))

Crimes_2010_Present <- left_join(Crimes_2010_to_Present, IUCR_Codes, by = "IUCR") |>
  filter(Year < 2020)
```

```{r}
Illinois_Crime_Trends_Plot <- Illinois_Crime_Stats |>
  filter(Year < 2020) |>
  mutate(`Chicago Reported Rate` = (CPD_Reported_TIC /(`CPD_Reported Population`/100000)),
         `Chicago DataPortal Rate` = (Data_Portal_TIC /(`CPD_Reported Population`/100000)),
         `Illinois Non-Chicago Rate` = (Non_Chicago_Reported_TIC /(Non_Chicago_Population/100000)),
         `Illinois Rate` = (Illinois_TIX_Offenses/(`Illinois_Population`/100000))) |>
  select(Year,
         `Chicago Reported Rate`,
         `Chicago DataPortal Rate`,
         `Illinois Non-Chicago Rate`,
         `Illinois Rate`) |>
  pivot_longer(cols = c(`Chicago Reported Rate`,
                        `Chicago DataPortal Rate`,
                        `Illinois Non-Chicago Rate`,
                        `Illinois Rate`), 
               names_to = "Area",
               values_to = "Rate_Per_100000") |>
ggplot(aes(x = Year, y = Rate_Per_100000, fill = Area)) +
  geom_point(aes(color = Area), size = 1) +
  geom_line(aes(color = Area)) +
  scale_x_continuous(breaks = seq(2010, 2019, by = 1)) +
  labs(title = "Illinois Crime Trends from 2010-2019",
       x = "Year",
       y = "Crime Per 100,000") +
  theme(
    legend.title = element_text(size = 18, face = "bold"),
    legend.text = element_text(size = 16),
    plot.title = element_text(size = 24, face = "bold"),
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    axis.text.x = element_text(size = 14),
    axis.text.y = element_text(size = 14)
  )

ggsave("Illinois_Crime_Trends_Plot.png", 
       plot = Illinois_Crime_Trends_Plot,
       width = 4,
       height = 2.25)
```

-----------------------------------------------------
#DIFFERENCE IN DIFFERENCE ANALYSIS
-----------------------------------------------------

```{r}
reported_population <- Illinois_Crime_Stats |>
  filter(Year != 2020) |>
  select(Year, Non_Chicago_Population, `CPD_Reported Population`) |>
  rename(Non_Chicago = Non_Chicago_Population,
         Chicago = `CPD_Reported Population`) |>
  pivot_longer(cols = c(Non_Chicago, Chicago),
               names_to = "Area",
               values_to = "Population")
```

```{r}
# DID analysis - using CPD reported Crime statistics
reported_DID <- Illinois_Crime_Stats |>
  filter(Year != 2020) |>
  select(Year, Non_Chicago_Reported_TIC, CPD_Reported_TIC) |>
  rename(Non_Chicago = Non_Chicago_Reported_TIC,
         Chicago = CPD_Reported_TIC)
```

```{r}
reported_DID <- reported_DID |>
  pivot_longer(cols = c(Non_Chicago, Chicago), names_to = "Area") |>
  #create a dummy variable for when the treatment started
  mutate(time = ifelse(Year > 2012, 1, 0)) |>
  #create a dummy variable for geographic area treated
  mutate(treated = ifelse(Area == "Chicago", 1, 0)) |>
  #create an interaction between time and treated variables
  mutate(did = time*treated)
```

```{r}
reported_DID <- left_join(reported_DID, reported_population, by = c("Area", "Year"))
```


```{r}
#Estimate the DID Estimator
reported_DID$Population <- as.numeric(unlist(reported_DID$Population))

didreg = lm(value ~ treated + time + did + Population, data = reported_DID)
summary(didreg)
```

```{r}
# Export results to LaTeX (or Word)
stargazer(didreg, type = "latex", out = "DID_results.tex")  # To export LaTeX
# stargazer(fe_model, type = "text", out = "DID_results.txt")  # To export text
```

```{r}
# DID analysis - using CPD reported Crime Rate for population
reported_rate_DID <- Illinois_Crime_Stats |>
  filter(Year != 2020) |>
  select(Year, Non_Chicago_Reported_TIC, Non_Chicago_Population, CPD_Reported_TIC, `CPD_Reported Population`) |>
  mutate(Non_Chicago_CrimePer = Non_Chicago_Reported_TIC/(Non_Chicago_Population/100000),
         Chicago_CrimePer = CPD_Reported_TIC/(`CPD_Reported Population`/100000)) |>
  select(Year, Non_Chicago_CrimePer, Chicago_CrimePer)
```

```{r}
reported_rate_DID <- reported_rate_DID |>
  pivot_longer(cols = c(Non_Chicago_CrimePer, Chicago_CrimePer), names_to = "Area") |>
  #create a dummy variable for when the treatment started
  mutate(time = ifelse(Year > 2012, 1, 0)) |>
  #create a dummy variable for geographic area treated
  mutate(treated = ifelse(Area == "Chicago_CrimePer", 1, 0)) |>
  #create an interaction between time and treated variables
  mutate(did = time*treated)
```

```{r}
didreg_rate = lm(value ~ treated + time + did, data = reported_rate_DID)
summary(didreg_rate)
```

```{r}
# Export results to LaTeX (or Word)
stargazer(didreg_rate, type = "latex", out = "DID_results.tex")  # To export LaTeX
# stargazer(fe_model, type = "text", out = "DID_results.txt")  # To export text
```

