---
title: "SSL"
output: html_document
date: "2025-04-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(dplyr)
library(RColorBrewer)
library(colorspace)

options(scipen = 999)
options(digits = 2)
file_path <- dirname(getwd())
palette_30 <- qualitative_hcl(30, palette = "Dark 3")  # Or try "Set 2", "Harmonic", etc.
```

```{r}
#load in SSL Dataset
Strategic_Subject_List_Historical <- read_csv(file.path(file_path, "Raw Data",  "Strategic_Subject_List_-_Historical_20241107.csv"))
```

```{r}
#Standardize Districts
Strategic_Subject_List_Historical <- Strategic_Subject_List_Historical |>
  mutate(District = `LATEST DIST RES`) |>
  #consolidate district 13 into 12
  mutate(District = ifelse((District == 13), 12, District)) |>
  #consolidate district 21 into 2
  mutate(District = ifelse((District == 21), 2, District)) |>
  #consolidate district 23 into 19
  mutate(District = ifelse((District == 23), 19, District)) 
```

----------------------
#Summary Statistics
-----------------------

```{r}
#Mean and Median of SSL Score by District
SSL_stats <- Strategic_Subject_List_Historical |>
  group_by(District) |>
  summarise(Count = n(),
            Mean = mean(`SSL SCORE`),
            Median = median(`SSL SCORE`))

write.csv(SSL_stats, "SSL_stats.csv")
```

```{r}
Strategic_Subject_List_Historical |>
  summarise(min = min(`PREDICTOR RAT TREND IN CRIMINAL ACTIVITY`),
            max = max(`PREDICTOR RAT TREND IN CRIMINAL ACTIVITY`))
```

----------------------
#Box and Whisker Plot
---------------------
```{r}
SSL_top20_stats <- Strategic_Subject_List_Historical |>
  group_by(`District`) |>
  slice_max(order_by = `HEAT SCORE`, n = 20)|>
  group_by(District) |>
  summarise(
    Q1 = quantile(`SSL SCORE`, 0.25, na.rm = TRUE),
    Median = median(`SSL SCORE`, na.rm = TRUE),
    Q3 = quantile(`SSL SCORE`, 0.75, na.rm = TRUE),
    Mean = mean(`SSL SCORE`, na.rm = TRUE),
    count = n()
  )

write.csv(SSL_top20_stats, "SSL_top20_stats.csv")
```

```{r}
SSL_top20 <- Strategic_Subject_List_Historical |>
  group_by(`District`) |>
  slice_max(order_by = `HEAT SCORE`, n = 20)
```

```{r}
#Add a boolean to the full Dataset that signifies whether an individual was in the top 20
# Save the District + HEAT SCORE combos
Top20_keys <- SSL_top20 |>
  select(District, `HEAT SCORE`)

# Flag in the full dataset
Strategic_Subject_List_Historical <- Strategic_Subject_List_Historical |>
  mutate(in_top20 = (paste(District, `HEAT SCORE`) %in% 
                     paste(Top20_keys$District, Top20_keys$`HEAT SCORE`)))

Strategic_Subject_List_Historical_non_Top_20 <- Strategic_Subject_List_Historical |>
  filter(in_top20 == FALSE)

```

```{r}
# Step 1: Prepare data

plot_data <- SSL_top20 |>
  mutate(
    medianscore = ave(`HEAT SCORE`, `District`, FUN = median),
    counts = ave(`HEAT SCORE`, `District`, FUN = length)
  ) |>
  mutate(
    label = reorder(sprintf("District %s (N=%d)", `District`, counts), `District`)
  )
```

```{r}
Heat_Score_Distribution <- ggplot(plot_data, aes(y = label, x = `HEAT SCORE`, color = factor(`District`))) +
  geom_boxplot(outlier.color = NA, color = "black") +
  geom_point(position = position_jitter(height = 0.3, width = 0.01), alpha = 0.7, aes(color = factor(`District`))) +
  scale_color_manual(values = palette_30)+
  #scale_color_viridis_d(option = "C", direction = -1) +
  theme_bw() +
  geom_vline(xintercept = median(plot_data$`HEAT SCORE`, na.rm = TRUE), lty = "dashed") +
  labs(x = "HEAT SCORE", y = "Police District (N)", title = "Distribution of HEAT SCORE by Police District") +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold"),
        axis.title = element_text(face = "bold")) +  

ggsave("Heat_Score_Distribution.png", 
       plot = Heat_Score_Distribution,
       width = 4,
       height = 6, 
       dpi = 500)

#Median is 479
```

```{r}
District_population |>
  group_by(District) |>
  summarise(TIC = mean(TIC),
            Crime_per_1000 = mean(Crime_per_1000))
```
---------------
#Majority
----------------

```{r}
#252670 have a majority dist
#141973	have a majority district that doesn't match their district of residence
Strategic_Subject_List_Historical |>
  filter(!is.na(`MAJORITY DIST`)) |>
  #filter to individuals where majority district doesn't match up with district on file
  filter(`MAJORITY DIST` != District) |>
  group_by(`MAJORITY DIST`) |>
  summarise(count = n())

Strategic_Subject_List_Historical |>
  filter(!is.na(`MAJORITY DIST`)) |>
  #filter to individuals where majority district doesn't match up with district on file
  filter(`MAJORITY DIST` != District) |>
  group_by(District) |>
  summarise(count = n())
  
Strategic_Subject_List_Historical |>
  filter(!is.na(`MAJORITY DIST`)) |>
  #filter to individuals where majority district doesn't match up with district on file
  filter(`MAJORITY DIST` != District) |>
  group_by(`MAJORITY DIST`, District) |>
  summarise(count = n())
```

```{r}
Strategic_Subject_List_Historical |>
  filter(!is.na(`MAJORITY DIST`)) |>
  #filter to individuals where majority district doesn't match up with district on file
  filter(`MAJORITY DIST` != District) |>
  group_by(`MAJORITY DIST`, District) |>
  summarise(count = n())
```

```{r}
Strategic_Subject_List_Historical|>
  filter(!is.na(`MAJORITY DIST`)) |>
  #filter to individuals where majority district doesn't match up with district on file
  filter(`MAJORITY DIST` != District) |>
  group_by(`MAJORITY DIST`, District) |>
  filter(District == 31) |>
  summarise(count = n())
```


-----------------
#SSL FLAGS - interactions with Police Units
------------------

```{r}
Strategic_Subject_List_Historical |>
  filter(!is.na(`SSL FLAGS`)) |>
  group_by(District) |>
  summarise(count = n())

  group_by(`SSL FLAGS`) |>
  summarize(count = n())
```
-----------------------------
#AGE
-----------------------------

```{r}
#Distribution of top 20 SSL
SSL_top20 |>
  group_by(`AGE GROUP`) |>
    summarise(
    Q1 = quantile(`SSL SCORE`, 0.25, na.rm = TRUE),
    Median = median(`SSL SCORE`, na.rm = TRUE),
    Q3 = quantile(`SSL SCORE`, 0.75, na.rm = TRUE),
    Mean = mean(`SSL SCORE`, na.rm = TRUE),
    count = n()
  )
```

```{r}
#Age distribution of full SSL dataset
Strategic_Subject_List_Historical |>
  group_by(`AGE GROUP`) |>
    summarise(
    Q1 = quantile(`SSL SCORE`, 0.25, na.rm = TRUE),
    Median = median(`SSL SCORE`, na.rm = TRUE),
    Q3 = quantile(`SSL SCORE`, 0.75, na.rm = TRUE),
    Mean = mean(`SSL SCORE`, na.rm = TRUE),
    count = n()
  )
```

```{r}
SSL_top20 |>
  group_by(`SEX CODE CD`) |>
  summarize(count = n())
```

```{r}
Strategic_Subject_List_Historical |>
  group_by(`SEX CODE CD`) |>
  summarize(count = n())
```



---------------------
#TOP 20 SSL Predictors
---------------------
```{r Age at latest}
SSL_top20 |>
  group_by(`PREDICTOR RAT AGE AT LATEST ARREST`) |>
  summarise(Count = n()) |>
  mutate(prop = Count/sum(Count))
```
```{r Current}
SSL_top20 |>
  group_by(`AGE CURR`) |>
  summarise(Count = n()) |>
  mutate(prop = Count/sum(Count))

Strategic_Subject_List_Historical |>
  group_by(`AGE CURR`) |>
  summarise(Count = n()) |>
  mutate(prop = Count/sum(Count))
```

```{r Race top 20}
SSL_top20 |>
  group_by(`RACE CODE CD`) |>
  summarise(Count = n()) |>
  mutate(prop = Count/sum(Count))
```
```{r Race full}
Strategic_Subject_List_Historical |>
  group_by(`RACE CODE CD`) |>
  summarise(Count = n()) |>
  mutate(prop = Count/sum(Count))
```

```{r Sex}
SSL_top20 |>
  group_by(`SEX CODE CD`) |>
  summarise(Count = n()) |>
  mutate(prop = Count/sum(Count))
```

```{r Num times victim of shooting top 20}
Strategic_Subject_List_Historical |>
  group_by(`PREDICTOR RAT VICTIM SHOOTING INCIDENTS`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r Num times victim of shooting rest of dataset}
Strategic_Subject_List_Historical_non_Top_20 |>
  group_by(`PREDICTOR RAT VICTIM SHOOTING INCIDENTS`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r Num times victim of assault top 20}
SSL_top20 |>
  group_by(`PREDICTOR RAT VICTIM BATTERY OR ASSAULT`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r Num times victim of assault full dataset}
Strategic_Subject_List_Historical |>
  group_by(`PREDICTOR RAT VICTIM BATTERY OR ASSAULT`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r Num Arrests Violent Offenses top 20}
SSL_top20 |>
  group_by(`PREDICTOR RAT ARRESTS VIOLENT OFFENSES`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r Num Arrests Violent Offenses full dataset}
Strategic_Subject_List_Historical |>
  group_by(`PREDICTOR RAT ARRESTS VIOLENT OFFENSES`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r gang affiliation top 20}
#boolean
SSL_top20 |>
  group_by(`PREDICTOR RAT GANG AFFILIATION`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r gang affiliation full dataset}
#boolean
Strategic_Subject_List_Historical |>
  group_by(`PREDICTOR RAT GANG AFFILIATION`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```


```{r Num times arrested for narcotics top 20}
SSL_top20 |>
  group_by(`PREDICTOR RAT NARCOTIC ARRESTS`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r Num times arrested for narcotics full dataset}
Strategic_Subject_List_Historical |>
  group_by(`PREDICTOR RAT NARCOTIC ARRESTS`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r Predictor trend in Criminal Activity}
SSL_top20 |>
  cut(SSL_top20$`PREDICTOR RAT TREND IN CRIMINAL ACTIVITY`, breaks = 6)
  summarise(quantile())
  ggplot(aes(x = `PREDICTOR RAT TREND IN CRIMINAL ACTIVITY`, y = `SSL SCORE`)) +
  geom_point()


SSL_top20 |>
  mutate(Pred_Crim = cut(`PREDICTOR RAT TREND IN CRIMINAL ACTIVITY`, 
                        breaks = c(-10, -5, -2, 0, 2, 5, 10), 
                        labels = c("Below -5", "[-5,-2]", "[-2,0]", "[0,2]", "[2,5]", "Above 5"),
                        right = TRUE)) |>
  group_by(Pred_Crim) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r Predictor trend in Criminal Activity full dataset}
Strategic_Subject_List_Historical |>
  cut(SSL_top20$`PREDICTOR RAT TREND IN CRIMINAL ACTIVITY`, breaks = 6)
  summarise(quantile())
  ggplot(aes(x = `PREDICTOR RAT TREND IN CRIMINAL ACTIVITY`, y = `SSL SCORE`)) +
  geom_point()


Strategic_Subject_List_Historical |>
  mutate(Pred_Crim = cut(`PREDICTOR RAT TREND IN CRIMINAL ACTIVITY`, 
                        breaks = c(-10, -5, -2, 0, 2, 5, 10), 
                        labels = c("Below -5", "[-5,-2]", "[-2,0]", "[0,2]", "[2,5]", "Above 5"),
                        right = TRUE)) |>
  group_by(Pred_Crim) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```

```{r Num of UUW Arrests top 20}
SSL_top20 |>
  group_by(`PREDICTOR RAT UUW ARRESTS`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```
```{r Num of UUW Arrests full dataset}
Strategic_Subject_List_Historical |>
  group_by(`PREDICTOR RAT UUW ARRESTS`) |>
  summarise(Count = n(),
            Mean_Score = mean(`SSL SCORE`),
            Max = max(`SSL SCORE`),
            Min = min(`SSL SCORE`)) |>
  mutate(Prop = Count/sum(Count))
```


```{r}
SSL_top20 |>
  filter(`SSL SCORE` < 500) |>
  ggplot(aes(x = `RAW SSL SCORE`, y = `SSL SCORE`)) +
  geom_point()

(SSL_top20 |>
  filter(`SSL SCORE` < 500))

model <- lm(log(`SSL SCORE`) ~ log(`RAW SSL SCORE`), data = filter(SSL_top20, `SSL SCORE` < 500))

summary(model)
```
```{r}
SSL_top20 |>
  group_by(`SSL FLAGS`) |>
  summarize(count = n())

#314 na values, 473 total
```






